# Generated by Django 4.2.4 on 2023-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(blank=True, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='perevalareas',
            name='id_parent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(verbose_name='телефон'),
        ),
    ]
