# Generated by Django 4.2.4 on 2023-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_coords_height_alter_perevalareas_id_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='телефон'),
        ),
    ]
