# Generated by Django 4.2.4 on 2023-11-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_remove_perevaladded_images_images_pereval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='autumn_lvl',
            new_name='autumn',
        ),
        migrations.RenameField(
            model_name='perevaladded',
            old_name='spring_lvl',
            new_name='spring',
        ),
        migrations.RenameField(
            model_name='perevaladded',
            old_name='summer_lvl',
            new_name='summer',
        ),
        migrations.RenameField(
            model_name='perevaladded',
            old_name='winter_lvl',
            new_name='winter',
        ),
    ]
