# Generated by Django 4.2.4 on 2023-11-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_rename_autumn_lvl_perevaladded_autumn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevalimages',
            old_name='id_images',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='images',
            name='pereval',
        ),
        migrations.RemoveField(
            model_name='perevalimages',
            name='id_pereval',
        ),
        migrations.AddField(
            model_name='perevalimages',
            name='pereval',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pereval.perevaladded'),
        ),
    ]
